### ISSUE TITLE
fix readstb abi after locking merges

### ISSUE THREAD

**Issue by ulda** [coburnw/python-vxi11-server#18]
hi coburn

you missed one api change on merging the locking code.
see #https://github.com/coburnw/python-vxi11-server/commit/18562b2db910d4c3b4bbc6ee39e35f1409b9e064
and maybe pull this 

bye
Ulf

**Comment by coburnw** [comment]
Huh. now thats never happened before...;
Thank you.

**Comment by ulda** [comment]
Oh yes, I understand  - and this conversation has never happened   .-D
