### ISSUE TITLE
missing link_id parameter in instrument_server.py handle_15(), line 319

### ISSUE THREAD

**Issue by ic17b033** [coburnw/python-vxi11-server#7]
There is the link_id parameter missing when calling self.device.device_clear(flags, lock_timeout, io_timeout) at line 319 in instrument_server.py in handle15().

**Comment by coburnw** [comment]
This seems true for several other methods in Vxi11CoreHandler also.  Thank you for the heads up.  

But Im having a hard time thinking of an instance when a device might need to know its link_id.  Perhaps this would be best handled by removing the parameter from the InstrumentDevice base class methods instead (and cleaning up the matching Vxi11CoreHandler of course).

Have you come across a need for an instrument_device to know its link_id?

**Comment by ic17b033** [comment]
No, i don't need the link_id in my application. I'm relatively new to python, so I only cared about the reason why I've got an error when device_readstb() and device_clear() were called

**Comment by coburnw** [comment]
link_id was removed from all InstrumentDevice calls and are now handled by the CoreHandler.
